# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: "pcdsdevices"
  python_name: "pcdsdevices"
  version: "v8.8.1"

package:
  name: "pcdsdevices"
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: pip install . -vv

requirements:
  build:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - bluesky-base >=1.6.4
    - happi
    - jsonschema
    - lightpath-base >=1.0.5
    - matplotlib-base
    - numpy
    - ophyd >=1.7.0
    - pcdscalc >=0.2.0
    - pcdsutils >=0.4.0
    - prettytable
    - pyepics >=3.4.2
    - pytmc >=2.7.0
    - pyyaml
    - schema
    - scipy
    - sympy
  run_constraints:
    - pmgr >=2.0.2
    - typhos >=2.4.0

tests:
  - script:
    - pytest
    requirements:
      run:
        - pytest
        - pytest-timeout
        - typhos
    files:
      source:
        - pcdsdevices/

about:
  homepage: https://github.com/pcdshub/pcdsdevices
  license: LicenseRef-SLACOpenLicense
  license_file: LICENSE.md
  summary: IOC definitions for LCLS Beamline Devices
